### ISSUE TITLE
[BUG] - Using TV Static preset, set Pixel width and height to full source size doesn't fill the source

### ISSUE THREAD

**Issue by tyronesluck** [FiniteSingularity/obs-noise#7]
**Describe the bug**
Using TV Static preset, set Pixel width and height to full source size doesn't fill the source.

**To Reproduce**
1. Set Source properties to 1920px by 1080px
2. Go to Preset and set it to "TV Static"
3. Set Base Pixel Width to 1920px
4. Set Base Pixel Height to 1080px
5. The noise doesn't fill the 1920px by 1080px source

**Expected behavior**
The noise should fill the full size of the source

**Screenshots**
Screen shot attached.

**Environment**
 - OS/Version: Windows 10
 - OBS Version: 30.0.2
 - Noise : v0.0.3a
 - Preset : TV Static

**GPU**
 - GPU make/model : RX580
 - GPU VRAM : 8GB

![Screenshot 2024-01-10 171930](https://github.com/FiniteSingularity/obs-noise/assets/105045950/664d5ad4-7dbd-4635-a7b6-618a88190a53)

**Comment by FiniteSingularity** [comment]
In this case it isn't a bug, but is somewhat "as intended" math-wise.  The pixel size is actually correct, however due to how the math works, the origin of where the noise pattern starts is offset. In your image above, the black pixel goes off the left and top of the frame.  In the next version of the plugin, you'll see a "Base Offset" x and y value, which lets the user shift the noise field, and you'll find that if you set the offset correctly, those pixels will fill the frame.  You can see the results here:
![image](https://github.com/FiniteSingularity/obs-noise/assets/72580859/cabddb4b-69db-4d87-bd1c-55bc5a075812)
